root='e:/Matlab/Simulink/S-Function_16';
S2=load(fullfile(root,'results','bo_results','phase2_best.mat'));
cm=S2.best.ctrl_maps;
fprintf('umin_range=\n'); disp(cm.umin_range);
fprintf('umax_range=\n'); disp(cm.umax_range);
fprintf('scale_umin_lo=\n'); disp(cm.scale_umin_lo);
fprintf('scale_umin_hi=\n'); disp(cm.scale_umin_hi);
fprintf('scale_umax_lo=\n'); disp(cm.scale_umax_lo);
fprintf('scale_umax_hi=\n'); disp(cm.scale_umax_hi);
if isfield(cm,'enable_weight_interp'), fprintf('enable_weight_interp=%d\n', cm.enable_weight_interp); end
